# Generated by Django 4.2.8 on 2023-12-26 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Напишите название')),
                ('image', models.ImageField(upload_to='', verbose_name='Добавьте изоброжение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(5000)], verbose_name='Укажите цену')),
                ('genre', models.CharField(choices=[('Комедия', 'Комедия'), ('Мультфильмы', 'Мультфильмы'), ('Дорамы', 'Дорамы')], max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('trailer', models.URLField(verbose_name='Добавьте ссылку на трейлер')),
                ('book_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
