# Generated by Django 4.2.8 on 2023-12-27 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Напишите название')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Напишите название')),
                ('image', models.ImageField(upload_to='', verbose_name='Добавьте изоброжение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(5000)], verbose_name='Укажите цену')),
                ('genre', models.CharField(choices=[('Комедия', 'Комедия'), ('Мультфильм', 'Мультфильм'), ('Дорама', 'Дорама')], max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('trailer', models.URLField(verbose_name='Добавьте ссылку на трейлер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tv_shows.category')),
            ],
        ),
    ]
