# Generated by Django 4.2.8 on 2023-12-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='book_created_at',
            new_name='created_at',
        ),
    ]
