# Generated by Django 4.2.8 on 2023-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_alter_show_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.CharField(choices=[('романтика', 'романтика'), ('боевик', 'боевик'), ('фэнтэзи', 'фэнтэзи'), ('приключения', 'приключения')], max_length=50),
        ),
    ]
