# Generated by Django 4.2.8 on 2023-12-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_rename_book_created_at_show_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.CharField(choices=[('Комедия', 'Комедия'), ('Мультфильм', 'Мультфильм'), ('Дорама', 'Дорама')], max_length=50),
        ),
    ]
